services:
  dbms:
   image: postgres
   environment:
     TZ: ${OS_TIMEZONE}
     POSTGRES_DB: ${DB_NAME}
     POSTGRES_USER: ${DB_USER}
     POSTGRES_PASSWORD: ${DB_PASSWORD}
     PGDATA: /var/lib/postgresql/data/pgdata
   ports:
     - ${DB_PORT}:5432
   volumes:
     - ./postgres:/docker-entrypoint-initdb.d